# Site settings
title:             "Martin Micunda"
subtitle:          "Full Stack Software Engineer"
bio:               "Martin Micunda is a Full Stack Software Engineer based in Dublin, Ireland."
baseurl:           "" # the subpath of your site, e.g. /blog/
url:               http://martinmicunda.com
cover_image:       blog-cover.jpg?15867
logo:              logo.png
company:           Martin Micunda
github_username:   martinmicunda
twitter_username:  martinmicunda
linkedin_username: martinmicunda

# Comments
disqus:
  # Eg. "exampleblog" Set to false to disable comments
  shortname:  martinmicunda


# Google Fonts
# eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
google_font: 'Droid+Sans:400,700'

permalink:     pretty
paginate_path: 'page:num'
paginate:      10

markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]